name: "gradle-wrapper-validation"
on:
  workflow_call:

permissions:
  contents: read

jobs:
  gradle_wrapper_validation:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
